services:
  pacayadb:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres 
    ports:
      - "5432:5432"

  superset:
    image: apache/superset
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
    ports:
      - "8088:8088"    
    depends_on:
      - pacayadb


